using System;

namespace CS2MultiplayerMod.Game.Sync.Infrastructure
{
    /// <summary>
    /// Reproduces the vertical profile a net course commits to, and decides how a replicated span
    /// can be reproduced on another machine.
    /// <para>
    /// Only the two endpoints of a course travel; the deck between them is regenerated by the
    /// receiver, which samples its own terrain AND its own water every few metres. Terrain is
    /// replicated, water is live simulation state and is not, so a span over water lands at whatever
    /// height the realizing machine's water happens to be. Removing the local surface from the span
    /// is the fix: endpoint elevations at or beyond the prefab's elevation limit collapse the
    /// generator's clamp band onto the two endpoint heights, which pins the deck to the straight
    /// line between them. A source deck that is not one straight line travels as several pinned
    /// pieces instead (see <see cref="Simplify"/>).
    /// </para>
    /// </summary>
    internal static class NetWaterProfilePin
    {
        /// <summary>Water shallower than this reads as terrain - the generator's own shore band.</summary>
        public const float ShoreDepth = 0.2f;

        /// <summary>Bridge clearance added above a bridged water surface, in elevation limits.</summary>
        public const float ClearanceLimits = 2f;

        /// <summary>Deck deviation (m) a single straight pin may absorb before the span is divided.</summary>
        public const float ChordTolerance = 1f;

        /// <summary>Metres between profile probes; the generator samples at the same spacing.</summary>
        public const float ProbeSpacing = 4f;

        /// <summary>Upper bound on probes per span, so a very long drag stays cheap.</summary>
        public const int ProbeCount = 65;

        /// <summary>Most pieces one source course may be divided into.</summary>
        public const int MaxPieces = 8;

        /// <summary>
        /// The height the generator measures a course elevation from: the terrain, or - where the
        /// water is deep enough to bridge - the water surface plus the prefab's bridge clearance.
        /// </summary>
        public static float SurfaceHeight(float terrain, float water, float depth, float elevationLimit)
        {
            float bridged = depth < ShoreDepth ? terrain : water + elevationLimit * ClearanceLimits;
            return Math.Max(terrain, bridged);
        }

        /// <summary>Probe count for a span of <paramref name="lengthXZ"/> metres, as the generator uses.</summary>
        public static int ProbesFor(float lengthXZ)
        {
            if (!(lengthXZ > 0f)) return 2;
            int probes = 1 + (int)Math.Ceiling(lengthXZ / ProbeSpacing);
            if (probes < 2) probes = 2;
            return probes > ProbeCount ? ProbeCount : probes;
        }

        public static bool CrossesWater(float[] depth, int count)
        {
            for (int i = 0; i < count; i++)
                if (depth[i] >= ShoreDepth) return true;
            return false;
        }

        /// <summary>
        /// The deck the local generator produces for this span, from per-probe surfaces. Mirrors
        /// course splitting: slope-limit passes in both directions, the two endpoint heights, the
        /// slope cone each endpoint casts along the span, and the straightening that replaces every
        /// run of raised probes with a line between the terrain-following probes bracketing it.
        /// </summary>
        public static void PredictDeck(float[] surface, float[] terrain, float[] distance, int count,
            float startHeight, float endHeight, float maxSlope, float[] deck)
        {
            if (count <= 0) return;
            for (int i = 0; i < count; i++) deck[i] = surface[i];
            if (count == 1) { deck[0] = startHeight; return; }

            float slope = maxSlope > 0f ? maxSlope : 0f;

            float run = float.NegativeInfinity;
            for (int i = 0; i < count; i++)
            {
                run -= distance[i] * slope;
                if (deck[i] < run) deck[i] = run;
                run = deck[i];
            }
            run = float.NegativeInfinity;
            for (int i = count - 1; i >= 0; i--)
            {
                if (deck[i] < run) deck[i] = run;
                run = deck[i] - distance[i] * slope;
            }

            deck[0] = startHeight;
            deck[count - 1] = endHeight;

            // Both endpoints cast a slope cone along the span and the deck is clamped into the
            // overlap. Where the two cones do not overlap the band collapses to one height, which
            // also anchors that probe against the straightening below.
            var anchored = new bool[count];
            anchored[0] = true;
            anchored[count - 1] = true;
            var fromStart = new float[count];
            float spanned = 0f;
            for (int i = 1; i < count; i++) { spanned += distance[i]; fromStart[i] = spanned; }

            spanned = 0f;
            for (int i = count - 2; i > 0; i--)
            {
                spanned += distance[i + 1];
                float low = Math.Max(startHeight - fromStart[i] * slope, endHeight - spanned * slope);
                float high = Math.Min(startHeight + fromStart[i] * slope, endHeight + spanned * slope);
                if (low > high)
                {
                    float t = fromStart[i] / Math.Max(1e-3f, fromStart[i] + spanned);
                    deck[i] = low + (high - low) * t;
                    anchored[i] = true;
                }
                else deck[i] = deck[i] < low ? low : (deck[i] > high ? high : deck[i]);
            }

            Straighten(terrain, distance, count, deck, anchored);
        }

        /// <summary>
        /// Divide the probe range into as few straight pieces as reproduce <paramref name="deck"/>
        /// within <paramref name="tolerance"/>. Returns the piece count; <paramref name="breaks"/>
        /// receives that many + 1 probe indices, always starting at 0 and ending at count - 1.
        /// </summary>
        public static int Simplify(float[] deck, float[] distance, int count, float tolerance,
            int maxPieces, int[] breaks)
        {
            breaks[0] = 0;
            if (count <= 2 || maxPieces <= 1)
            {
                breaks[1] = count > 1 ? count - 1 : 0;
                return 1;
            }

            int pieces = 0;
            int from = 0;
            while (from < count - 1 && pieces < maxPieces)
            {
                int to = count - 1;
                // Take the longest stretch this piece still holds within tolerance; the last piece
                // this course is allowed takes whatever is left.
                if (pieces < maxPieces - 1)
                    while (to > from + 1 && MaxDeviation(deck, distance, from, to) > tolerance) to--;
                breaks[++pieces] = to;
                from = to;
            }
            breaks[pieces] = count - 1;
            return pieces;
        }

        private static float MaxDeviation(float[] deck, float[] distance, int from, int to)
        {
            float spanned = 0f;
            for (int i = from + 1; i <= to; i++) spanned += distance[i];
            if (!(spanned > 0f)) return 0f;

            float worst = 0f;
            float walked = 0f;
            for (int i = from + 1; i < to; i++)
            {
                walked += distance[i];
                float chord = deck[from] + (deck[to] - deck[from]) * (walked / spanned);
                float error = Math.Abs(deck[i] - chord);
                if (error > worst) worst = error;
            }
            return worst;
        }

        /// <summary>
        /// Whether a pinned span can be committed for this prefab. Both endpoint heights must be the
        /// ones the source built at, and the prefab's own elevation range has to reach both pins.
        /// </summary>
        public static bool IsEligible(bool startPinnable, bool endPinnable, bool hasElevationRange,
            float rangeMin, float rangeMax, float elevationLimit)
        {
            if (!startPinnable || !endPinnable) return false;
            if (!(elevationLimit > 0f) || !hasElevationRange) return false;
            return rangeMin <= -elevationLimit && rangeMax >= elevationLimit;
        }

        /// <summary>
        /// The start elevation of a pinned course. Together with <see cref="PinnedEndElevation"/> it
        /// collapses the generator's clamp band onto the two endpoint heights: one end at or above
        /// +limit sets the band floor, one at or below -limit sets its ceiling, and neither end
        /// resolves its height against the local surface any more.
        /// </summary>
        public static float PinnedStartElevation(float elevationLimit) => elevationLimit;

        public static float PinnedEndElevation(float elevationLimit) => -elevationLimit;

        private static void Straighten(float[] terrain, float[] distance, int count, float[] deck,
            bool[] anchored)
        {
            int i = 1;
            while (i < count - 1)
            {
                if (deck[i] == terrain[i] || anchored[i]) { i++; continue; }

                int last = i;
                while (last + 1 < count - 1 && deck[last + 1] != terrain[last + 1] &&
                       !anchored[last + 1]) last++;

                float spanned = 0f;
                for (int j = i; j <= last + 1; j++) spanned += distance[j];
                if (spanned > 0f)
                {
                    float low = deck[i - 1];
                    float high = deck[last + 1];
                    float walked = 0f;
                    for (int j = i; j <= last; j++)
                    {
                        walked += distance[j];
                        deck[j] = low + (high - low) * (walked / spanned);
                    }
                }
                i = last + 2;
            }
        }


    }
}
