using System.Collections.Generic;
using Game.Net;
using Game.Prefabs;
using Game.Tools;
using Unity.Collections;
using Unity.Entities;
using CS2MultiplayerMod.Core.Diagnostics;
using CS2MultiplayerMod.Game.Diagnostics;
using CS2MultiplayerMod.Game.Sync.Commands;

namespace CS2MultiplayerMod.Game.Sync.Systems.Net
{
    // Reads the local net tool's gesture back out of its definitions, skipping the hidden
    // sub-networks it generates.
    public partial class NetSyncSystem
    {
        private const long CommittedSideEffectWindowMs = 5000;

        /// <summary>
        /// Refreshes the cached course definitions. An empty frame or Clear keeps the cache (a still or
        /// moving preview does not always regenerate); switching tools invalidates it.
        /// </summary>
        public void ObserveLocalNetDefinitions(NativeArray<Entity> definitions)
        {
            global::Game.Tools.ToolBaseSystem active = _toolSystem != null ? _toolSystem.activeTool : null;
            if (!(active is global::Game.Tools.NetToolSystem))
            {
                _cachedLocalCourses.Clear();
                _cachedLocalMixedOperation.Clear();
                _cachedFallbackOriginalEdges.Clear();
                _cachedMixedRejection = null;
                return;
            }

            // Already published this frame; do not seed a stale cache for the next click.
            if (_nativeApplyCapturedFrame == _realizeFrame) return;

            // An owner-linked graph is captured atomically by BuildSyncSystem.
            if (global::CS2MultiplayerMod.Game.Sync.Systems.NativeObjectGraph
                .HasNewTopLevelObjectRoot(EntityManager, definitions))
            {
                _cachedLocalCourses.Clear();
                _cachedLocalMixedOperation.Clear();
                _cachedFallbackOriginalEdges.Clear();
                _cachedMixedRejection = null;
                return;
            }

            var netTool = (global::Game.Tools.NetToolSystem)active;
            bool pointOperation = netTool.actualMode == global::Game.Tools.NetToolSystem.Mode.Point;

            var next = new List<NetPlacementCommand>();
            var mixed = new List<LocalNetToolOperationItem>();
            // One unrepresentable course voids the envelope; a partial one would also suppress the fallback.
            string rejection = null;
            int rejected = 0;
            int mutations = 0;
            int hiddenSubNets = 0;
            var rejectedOriginalEdges = new List<Entity>();
            for (int i = 0; i < definitions.Length; i++)
            {
                Entity entity = definitions[i];
                if (!EntityManager.Exists(entity) || !EntityManager.HasComponent<NetCourse>(entity) ||
                    !EntityManager.HasComponent<CreationDefinition>(entity)) continue;

                CreationDefinition definition = EntityManager.GetComponentData<CreationDefinition>(entity);
                if (EntityManager.HasComponent<OwnerDefinition>(entity))
                {
                    // Re-cut building connectors are a consequence of the edit and are regenerated by the receiver;
                    // only a visible owned course is content (BuildSync captures it).
                    if (IsGeneratedHiddenSubNet(definition))
                    {
                        hiddenSubNets++;
                        continue;
                    }
                    rejected++;
                    rejection = rejection ?? "carry an owner definition";
                    continue;
                }

                NetCourse course = EntityManager.GetComponentData<NetCourse>(entity);
                // Point-mode prefabs commit zero-length courses; other zero-length ones are cursor markers. The
                // threshold is the realize side's degenerate limit: sub-metre courses are real.
                if (course.m_Length < NetPlacementCommand.MinCourseLength && !pointOperation) continue;

                if (!IsPlainLocalNetDefinition(definition))
                {
                    LocalNetToolOperationItem mutation =
                        CaptureMixedMutationCommand(definition, course, out string unrepresentable);
                    if (mutation != null)
                    {
                        mixed.Add(mutation);
                        mutations++;
                    }
                    else if (unrepresentable != null)
                    {
                        rejected++;
                        rejection = rejection ?? unrepresentable;
                    }

                    Entity original = definition.m_Original;
                    // Keep every usable original: if another member voids the envelope, all of them fall back.
                    if (original != Entity.Null && EntityManager.Exists(original) &&
                        EntityManager.HasComponent<Edge>(original) &&
                        EntityManager.HasComponent<Curve>(original) &&
                        EntityManager.HasComponent<PrefabRef>(original) &&
                        !rejectedOriginalEdges.Contains(original))
                        rejectedOriginalEdges.Add(original);
                }
                else
                {
                    NetPlacementCommand command = CaptureDefinitionCommand(definition, course,
                        out string unrepresentable);
                    if (command == null)
                    {
                        if (unrepresentable == null) continue;
                        rejected++;
                        rejection = rejection ?? unrepresentable;
                        continue;
                    }
                    next.Add(command);
                    mixed.Add(new LocalNetToolOperationItem
                    {
                        CommandId = NetPlacementCommand.Id,
                        Placement = command,
                    });
                }

                if (next.Count > NetPlacementCommand.MaxCoursesPerOperation ||
                    mixed.Count > NetToolOperationCommand.MaxItems)
                {
                    rejected++;
                    rejection = "exceed the atomic net-operation item cap";
                    break;
                }
            }

            if (next.Count == 0)
            {
                // A mutation-only graph belongs to delete/replace; drop the older placement preview.
                if (mutations > 0 || rejected > 0)
                {
                    _cachedLocalCourses.Clear();
                    _cachedLocalMixedOperation.Clear();
                    _cachedFallbackOriginalEdges.Clear();
                    _cachedMixedRejection = null;
                }
                return;
            }

            _cachedLocalCourses.Clear();
            _cachedLocalMixedOperation.Clear();
            if (rejection == null && mutations == 0)
            {
                _cachedFallbackOriginalEdges.Clear();
                _cachedMixedRejection = null;
                _cachedLocalCourses.AddRange(next);
                return;
            }

            if (rejection == null)
            {
                // One native Apply: keep the definition order in one envelope.
                _cachedFallbackOriginalEdges.Clear();
                _cachedMixedRejection = null;
                _cachedLocalMixedOperation.AddRange(mixed);
                SyncLog.Trace(LogTopic.Nets, "net atomic mixed capture cached items=" + mixed.Count +
                    " placements=" + next.Count + " mutations=" + mutations +
                    (hiddenSubNets > 0 ? " hiddenSubNets=" + hiddenSubNets : string.Empty));
                return;
            }

            // Never fall back to separate delete/replace/final-edge streams; repair from a snapshot instead.
            _cachedFallbackOriginalEdges.Clear();
            _cachedFallbackOriginalEdges.AddRange(rejectedOriginalEdges);
            _cachedMixedRejection = rejection;

            SyncLog.Warn(LogTopic.Nets,
                "NetSync: local mixed net operation cannot be encoded atomically (" + rejected +
                " of " + (rejected + next.Count) + " courses " + rejection + "; " + hiddenSubNets +
                " generated connector(s) skipped); the legacy " +
                "fragmented fallback is disabled and world recovery will be requested " +
                "after Apply.");
        }

        /// <summary>
        /// Publishes the cached courses when the tool applies, before ToolOutputSystem, while preview Temps
        /// still expose every original the operation replaces.
        /// </summary>
        public void CaptureLocalNetApply() =>
            CaptureLocalNetApply(refreshStandingDefinitions: true, barrierRecovery: false);

        /// <summary>
        /// Last-chance capture after <see cref="global::Game.Tools.ToolOutputBarrier"/>; the buffered
        /// definitions were already observed, so do not replace them with the older standing graph.
        /// </summary>
        public void CaptureBufferedLocalNetApply() =>
            CaptureLocalNetApply(refreshStandingDefinitions: false, barrierRecovery: true);

        private void CaptureLocalNetApply(bool refreshStandingDefinitions, bool barrierRecovery)
        {
            MultiplayerService service = Mod.Service;
            if (service == null || !service.GameplaySyncReady ||
                _nativeApplyCapturedFrame == _realizeFrame)
                return;

            global::Game.Tools.ToolBaseSystem active = _toolSystem != null ? _toolSystem.activeTool : null;
            if (!(active is global::Game.Tools.NetToolSystem) ||
                active.applyMode != global::Game.Tools.ApplyMode.Apply) return;

            // Re-read the standing graph: a grid can regenerate every course on the click frame, and a stale
            // cache makes the fallback replay each edge separately. A net-owned object graph goes to BuildSync.
            if (refreshStandingDefinitions && !_standingLocalDefinitions.IsEmptyIgnoreFilter)
            {
                NativeArray<Entity> definitions =
                    _standingLocalDefinitions.ToEntityArray(Allocator.Temp);
                try
                {
                    ObserveLocalNetDefinitions(definitions);
                }
                finally
                {
                    definitions.Dispose();
                }
            }

            if (_cachedLocalMixedOperation.Count > 0)
            {
                CaptureAtomicMixedNetApply(service, barrierRecovery);
                return;
            }
            if (_cachedLocalCourses.Count == 0)
            {
                if (!HasUnrepresentableMixedOperation) return;
                RecordPlacementOriginals(service.NowMs);
                _atomicMixedOriginals.Clear();
                _atomicMixedOriginalsFrame = _realizeFrame;
                for (int i = 0; i < _cachedFallbackOriginalEdges.Count; i++)
                    _atomicMixedOriginals.Add(_cachedFallbackOriginalEdges[i]);
                service.RequestAutomaticWorldRecovery(ResyncReport.Create(
                    "mixed road operation could not be encoded atomically", "net",
                    ResyncEvidence.StreamLoss).About(_cachedMixedRejection ?? "local mixed operation")
                    .Tried("captured the entire native Apply before publishing any member")
                    .Fact("unrepresented course", _cachedMixedRejection)
                    .Fact("original edges", _cachedFallbackOriginalEdges.Count));
                SyncLog.Trace(LogTopic.Nets, "net mixed capture rejected; recovery requested" +
                    (barrierRecovery ? " source=barrier" : string.Empty));
                _cachedFallbackOriginalEdges.Clear();
                _cachedMixedRejection = null;
                _nativeApplyCapturedFrame = _realizeFrame;
                _atomicMixedApplyCapturedFrame = _realizeFrame;
                return;
            }

            // With a remote batch armed, BeginRealizeFrame stood it down; this local Apply commits and is sent.

            long now = service.NowMs;
            RecordPlacementOriginals(now);

            // A straight span carries its source grade, measured once at publish.
            PinStraightProfiles(_cachedLocalCourses);

            long operationId = _nextLocalNetOperationId++;
            if (_nextLocalNetOperationId <= 0) _nextLocalNetOperationId = 1;
            int count = _cachedLocalCourses.Count;
            var encoded = new List<byte[]>(count);
            try
            {
                // Encode everything first; an unusual definition falls back as a whole.
                for (int i = 0; i < count; i++)
                {
                    NetPlacementCommand command = _cachedLocalCourses[i];
                    command.OperationId = operationId;
                    command.CourseIndex = (short)i;
                    command.CourseCount = (short)count;
                    encoded.Add(command.Encode());
                }
            }
            catch (System.Exception ex)
            {
                _cachedLocalCourses.Clear();
                SyncLog.Warn(LogTopic.Nets, "NetSync intent capture could not encode operation; " +
                    "using final-edge capture: " + ex.Message);
                return;
            }

            int sent = 0;
            for (int i = 0; i < count; i++)
            {
                NetPlacementCommand command = _cachedLocalCourses[i];
                try
                {
                    service.Session.SendCommand(0, NetPlacementCommand.Id, encoded[i]);
                    RecordDiagnostic(command.PrefabName);
                    sent++;
                }
                catch (System.Exception ex)
                {
                    SyncLog.Warn(LogTopic.Nets, "NetSync intent capture dropped course " + i + "/" +
                        count + ": " + ex.Message);
                }
            }

            _cachedLocalCourses.Clear();
            // A partial envelope does not count as captured; final-edge capture stays on as the fallback.
            if (sent == count) _nativeApplyCapturedFrame = _realizeFrame;
            if (sent > 0)
                SyncLog.Trace(LogTopic.Nets, "net intent apply op=" + operationId + " courses=" +
                    sent + "/" + count + (barrierRecovery ? " source=barrier" : string.Empty));
        }

        /// <summary>
        /// One heterogeneous net-tool Apply as one command, so the receiver resolves and arms it together.
        /// </summary>
        private void CaptureAtomicMixedNetApply(MultiplayerService service, bool barrierRecovery)
        {
            long now = service.NowMs;
            RecordPlacementOriginals(now);
            long sideEffectExpiry = now + CommittedSideEffectWindowMs;
            _atomicMixedOriginals.Clear();
            _atomicMixedOriginalsFrame = _realizeFrame;
            for (int i = 0; i < _cachedLocalMixedOperation.Count; i++)
            {
                LocalNetToolOperationItem local = _cachedLocalMixedOperation[i];
                Entity original = local.Original;
                if (original != Entity.Null && EntityManager.Exists(original) &&
                    EntityManager.HasComponent<Edge>(original))
                {
                    _atomicMixedOriginals.Add(original);
                    if (local.CommandId == NetDeleteCommand.Id)
                        _committedNetSideEffects[original] = sideEffectExpiry;
                }
            }

            PinStraightProfiles(_cachedLocalMixedOperation);

            long operationId = _nextLocalNetOperationId++;
            if (_nextLocalNetOperationId <= 0) _nextLocalNetOperationId = 1;

            int itemCount = _cachedLocalMixedOperation.Count;
            int placementCount = 0;
            for (int i = 0; i < itemCount; i++)
                if (_cachedLocalMixedOperation[i].CommandId == NetPlacementCommand.Id)
                    placementCount++;

            bool sent = false;
            try
            {
                var items = new NetToolOperationItem[itemCount];
                int placementIndex = 0;
                for (int i = 0; i < itemCount; i++)
                {
                    LocalNetToolOperationItem local = _cachedLocalMixedOperation[i];
                    byte[] body;
                    switch (local.CommandId)
                    {
                        case NetPlacementCommand.Id:
                            local.Placement.OperationId = operationId;
                            local.Placement.CourseIndex = (short)placementIndex++;
                            local.Placement.CourseCount = (short)placementCount;
                            body = local.Placement.Encode();
                            break;
                        case NetDeleteCommand.Id:
                            body = local.Delete.Encode();
                            break;
                        case NetReplaceCommand.Id:
                            body = local.Replace.Encode();
                            break;
                        default:
                            throw new System.InvalidOperationException(
                                "Unsupported cached atomic net command " + local.CommandId + ".");
                    }
                    items[i] = new NetToolOperationItem
                    {
                        CommandId = local.CommandId,
                        Body = body,
                    };
                }

                var operation = new NetToolOperationCommand
                {
                    OperationId = operationId,
                    Items = items,
                };
                service.Session.SendCommand(0, NetToolOperationCommand.Id, operation.Encode());
                sent = true;

                for (int i = 0; i < itemCount; i++)
                {
                    NetPlacementCommand placement = _cachedLocalMixedOperation[i].Placement;
                    if (placement != null) RecordDiagnostic(placement.PrefabName);
                }
            }
            catch (System.Exception ex)
            {
                // Suppress legacy echoes even when sending fails; the peer is repaired from a snapshot.
                SyncLog.Warn(LogTopic.Nets, "NetSync atomic mixed apply could not be sent: " +
                    ex.Message);
                service.RequestAutomaticWorldRecovery("atomic mixed road operation could not be sent");
            }
            finally
            {
                _cachedLocalMixedOperation.Clear();
                _cachedLocalCourses.Clear();
                _cachedFallbackOriginalEdges.Clear();
                _cachedMixedRejection = null;
                _nativeApplyCapturedFrame = _realizeFrame;
                _atomicMixedApplyCapturedFrame = _realizeFrame;
            }

            SyncLog.Trace(LogTopic.Nets, "net atomic mixed apply op=" + operationId + " items=" +
                itemCount + " status=" + (sent ? "sent" : "recovery") +
                (barrierRecovery ? " source=barrier" : string.Empty));
        }

        /// <summary>
        /// An original edge recorded from a committing transaction; DeleteSync asks first so it is not
        /// sent twice.
        /// </summary>
        public bool ConsumeCommittedNetSideEffect(Entity edge, long now)
        {
            if (_atomicMixedOriginalsFrame == _realizeFrame &&
                _atomicMixedOriginals.Remove(edge)) return true;

            if (!_committedNetSideEffects.TryGetValue(edge, out long expires)) return false;
            _committedNetSideEffects.Remove(edge);
            return expires >= now;
        }

        /// <summary>
        /// A hidden connector course (driveway, lot path), new or re-cut. The receiver regenerates these
        /// from the visible net.
        /// </summary>
        private bool IsGeneratedHiddenSubNet(CreationDefinition definition)
        {
            if (IsHiddenNetPrefab(definition.m_Prefab)) return true;

            Entity original = definition.m_Original;
            if (original == Entity.Null || !EntityManager.Exists(original) ||
                !EntityManager.HasComponent<PrefabRef>(original)) return false;
            return IsHiddenNetPrefab(EntityManager.GetComponentData<PrefabRef>(original).m_Prefab);
        }

        private bool IsHiddenNetPrefab(Entity prefab)
        {
            if (prefab == Entity.Null) return false;
            string name = PrefabNameOf(prefab);
            return !string.IsNullOrEmpty(name) && name.StartsWith("Invisible");
        }

        private static bool IsPlainLocalNetDefinition(CreationDefinition definition)
        {
            const CreationFlags incompatible = CreationFlags.Permanent | CreationFlags.Delete |
                CreationFlags.Upgrade | CreationFlags.Relocate | CreationFlags.Recreate |
                CreationFlags.Repair | CreationFlags.Duplicate;
            return definition.m_Original == Entity.Null && definition.m_Owner == Entity.Null &&
                   definition.m_Attached == Entity.Null && (definition.m_Flags & incompatible) == 0;
        }
    }
}
