using System.Collections.Generic;
using Colossal.Mathematics;
using Game.Net;
using Game.Prefabs;
using Game.Simulation;
using Game.Tools;
using Unity.Entities;
using Unity.Mathematics;

using CS2MultiplayerMod.Core.Diagnostics;
using CS2MultiplayerMod.Game.Diagnostics;
using CS2MultiplayerMod.Game.Sync.Commands;
using CS2MultiplayerMod.Game.Sync.Infrastructure;

namespace CS2MultiplayerMod.Game.Sync.Systems.Net
{
    // Vertical-profile transport for NetSyncSystem. A course carries two endpoints; the deck between
    // them is regenerated by whichever machine realizes it, from ITS terrain and ITS water sampled
    // every ~4 m. Terrain is replicated, water is live simulation state and is not, so a span over
    // water lands at the realizing machine's water height - correct end nodes, wrong deck. Capture
    // measures the deck it is committing and hands the receiver a form that needs no water at all;
    // see NetWaterProfilePin for the generator behaviour this mirrors.
    public partial class NetSyncSystem
    {
        private readonly float[] _profileSurface = new float[NetWaterProfilePin.ProbeCount];
        private readonly float[] _profileTerrain = new float[NetWaterProfilePin.ProbeCount];
        private readonly float[] _profileDepth = new float[NetWaterProfilePin.ProbeCount];
        private readonly float[] _profileDistance = new float[NetWaterProfilePin.ProbeCount];
        private readonly float[] _profileDeck = new float[NetWaterProfilePin.ProbeCount];
        private readonly int[] _profileBreaks = new int[NetWaterProfilePin.MaxPieces + 1];

        // 5 s counters. Capture: spans over water this machine pinned, spans whose own elevation
        // already bands them, and spans whose deck is not one line and so travel unpinned. Realize:
        // pinned spans committed, and pins this machine had to refuse - a refused span rebuilds its
        // deck from local water again, so a standing figure here is worth chasing.
        private int _capPinnedSpans;
        private int _capSelfAnchoredSpans;
        private int _capBentDeckSpans;
        private int _rzPinnedSpans, _rzPinRefused;

        // Per-course trace for the span currently being measured. A deformed bridge is a
        // disagreement between two machines about numbers neither of them prints, so every course
        // that touches water reports the ones the deck is built from. Only water crossings, and at
        // most a handful per operation, so a normal build logs nothing.
        private const int MaxProfileTraceLines = 6;
        private int _profileTraceLines;
        private bool _profileTouchedWater;
        private bool _profileDeckReady;
        private bool _profileTraceWorthy;
        private string _profileVerdict;

        /// <summary>
        /// Mark every course of a captured operation whose deck this machine measures over water,
        /// so the receiver commits that deck instead of rebuilding one from its own water. Runs
        /// once, at publish: the probe reads the terrain and water surfaces, and the definition
        /// cache is rebuilt on every preview frame.
        /// </summary>
        private void PinWaterProfiles(List<NetPlacementCommand> courses)
        {
            _profileTraceLines = 0;
            for (int i = 0; i < courses.Count; i++) PinCapturedCourse(courses[i]);
        }

        /// <summary>
        /// The same for a mixed operation, whose placements are interleaved with deletes and
        /// replaces.
        /// </summary>
        private void PinWaterProfiles(List<LocalNetToolOperationItem> items)
        {
            _profileTraceLines = 0;
            for (int i = 0; i < items.Count; i++)
            {
                LocalNetToolOperationItem item = items[i];
                if (item.CommandId != NetPlacementCommand.Id || item.Placement == null) continue;
                PinCapturedCourse(item.Placement);
            }
        }

        /// <summary>
        /// Pin one captured course to the deck this machine is committing, when that deck is the
        /// straight line between its two endpoints - the one shape the receiver's generator
        /// reproduces from the endpoints alone. Both endpoint heights are already on the wire, so a
        /// pinned course is the captured command plus a flag and nothing else moves.
        /// <para>
        /// A deck with a real bend in it is left alone deliberately. Reproducing one would mean
        /// publishing the span as several pinned pieces, which gives the receiver a node and an edge
        /// per boundary that the source does not have, and pins stretches whose shape the receiver
        /// already derives from replicated terrain. What is left unpinned is the span whose deck
        /// follows the terrain between the water, and terrain travels.
        /// </para>
        /// </summary>
        private void PinCapturedCourse(NetPlacementCommand command)
        {
            int probes, pieces;
            _profileTouchedWater = false;
            _profileDeckReady = false;
            _profileTraceWorthy = false;
            _profileVerdict = null;

            bool pin = false;
            if (MeasurePinnableDeck(command, out probes, out pieces))
            {
                if (pieces == 1)
                {
                    pin = true;
                    _profileVerdict = "pin";
                }
                else
                {
                    _capBentDeckSpans++;
                    _profileVerdict = "deck needs " + pieces + " chords";
                }
            }
            TraceMeasuredSpan(command, probes);

            if (!pin) return;
            command.PinProfile = true;
            _capPinnedSpans++;
        }

        /// <summary>
        /// Report the numbers the deck of one water-crossing span was built from. Both machines run
        /// this same measurement, so two logs side by side say which input they disagree about - the
        /// water surface, the endpoint elevation, or the height the endpoint resolves to.
        /// </summary>
        private void TraceMeasuredSpan(NetPlacementCommand command, int probes)
        {
            if (!_profileTraceWorthy || _profileTraceLines >= MaxProfileTraceLines) return;
            _profileTraceLines++;

            float deckLow = 0f, deckHigh = 0f;
            float deckStart = command.Start.PosY, deckEnd = command.End.PosY;
            if (_profileDeckReady)
            {
                deckLow = float.MaxValue;
                deckHigh = float.MinValue;
                for (int i = 0; i < probes; i++)
                {
                    if (_profileDeck[i] < deckLow) deckLow = _profileDeck[i];
                    if (_profileDeck[i] > deckHigh) deckHigh = _profileDeck[i];
                }
                deckStart = _profileDeck[0];
                deckEnd = _profileDeck[probes - 1];
            }

            Entity prefab;
            NetPrefabInfo info = _prefabIndex.TryResolve(command.PrefabName, out prefab)
                ? NetInfoOf(prefab) : default(NetPrefabInfo);
            var startFlags = (CoursePosFlags)command.Start.Flags;
            var endFlags = (CoursePosFlags)command.End.Flags;

            SyncLog.Detail(LogTopic.Nets, "NetSync water span '" + command.PrefabName +
                "' limit=" + info.ElevationLimit.ToString("F2") +
                " slope=" + info.MaxSlopeSteepness.ToString("F2") +
                " probes=" + probes +
                " start[" + (((startFlags & CoursePosFlags.FreeHeight) != 0) ? "free" : "fixed") +
                " elev=" + command.Start.ElevationLeft.ToString("F2") +
                " wireY=" + command.Start.PosY.ToString("F2") +
                (_profileTouchedWater ? " surface=" + _profileSurface[0].ToString("F2") : "") +
                " ->Y=" + deckStart.ToString("F2") + "]" +
                " end[" + (((endFlags & CoursePosFlags.FreeHeight) != 0) ? "free" : "fixed") +
                " elev=" + command.End.ElevationLeft.ToString("F2") +
                " wireY=" + command.End.PosY.ToString("F2") +
                (_profileTouchedWater
                    ? " surface=" + _profileSurface[probes - 1].ToString("F2") : "") +
                " ->Y=" + deckEnd.ToString("F2") + "]" +
                (_profileDeckReady
                    ? " deck=" + deckLow.ToString("F2") + ".." + deckHigh.ToString("F2")
                    : "") +
                " -> " + (_profileVerdict ?? "not pinnable"));
        }

        /// <summary>
        /// Sample the deck this machine is committing for <paramref name="command"/> into the first
        /// <paramref name="probes"/> entries of <see cref="_profileDeck"/>, and report how many
        /// straight pieces it takes to hold that deck within tolerance. False when the span never
        /// touches water or cannot be pinned at all - the caller then sends it exactly as captured.
        /// </summary>
        private bool MeasurePinnableDeck(NetPlacementCommand command, out int probes, out int pieces)
        {
            probes = 0;
            pieces = 0;
            if (!command.HasNativeCourse || command.PinProfile) return false;
            _profileVerdict = null;

            // A fixed-element net (a dam) is divided by its own element table and must not be
            // pre-divided here; an owned sub-net already commits at its absolute height, and a
            // tunnel measures against the terrain alone. None of the three depends on water.
            if (command.FixedIndex >= 0) { _profileVerdict = "fixed-element net"; return false; }
            if (command.Start.ParentMesh >= 0 || command.End.ParentMesh >= 0)
            { _profileVerdict = "owned sub-net"; return false; }
            if (command.Start.ElevationLeft < -1f || command.End.ElevationLeft < -1f)
            { _profileVerdict = "tunnel"; return false; }

            Entity prefab;
            if (!_prefabIndex.TryResolve(command.PrefabName, out prefab))
            { _profileVerdict = "unknown prefab"; return false; }
            NetPrefabInfo info = NetInfoOf(prefab);

            // A span whose own elevation bands its deck - a bridge raised a full elevation step or
            // more, on two fixed-height ends - already reproduces: the generator holds every probe
            // between the two transmitted endpoint heights, and those travel exactly. Pinning it
            // would swap a deck the receiver derives correctly for one measured here. A free-height
            // end takes that guarantee away: the band is anchored at the height the REALIZING
            // machine resolves, so the span moves with its water however raised it looks.
            if (!NetWaterProfilePin.NeedsPin(command.Start.ElevationLeft, command.End.ElevationLeft,
                    info.ElevationLimit, info.RequireElevated,
                    ((CoursePosFlags)command.Start.Flags & CoursePosFlags.FreeHeight) != 0,
                    ((CoursePosFlags)command.End.Flags & CoursePosFlags.FreeHeight) != 0))
            {
                _capSelfAnchoredSpans++;
                _profileVerdict = "own elevation bands the deck";
                _profileTraceWorthy = true;
                return false;
            }

            if (!NetWaterProfilePin.IsEligible(true, true, info.HasElevationRange,
                    info.ElevationRangeMin, info.ElevationRangeMax, info.ElevationLimit))
            { _profileVerdict = "prefab elevation range too narrow"; return false; }

            float2 range = new float2(command.Start.CourseDelta, command.End.CourseDelta);
            if (!math.isfinite(range.x) || !math.isfinite(range.y) || range.y <= range.x) return false;

            Bezier4x3 source = SourceCurve(command);
            float lengthXZ = MathUtils.Length(MathUtils.Cut(source, range).xz);
            if (!(lengthXZ > NetPlacementCommand.MinCourseLength)) return false;

            var startPosition = new float3(command.Start.PosX, command.Start.PosY, command.Start.PosZ);
            var endPosition = new float3(command.End.PosX, command.End.PosY, command.End.PosZ);

            TerrainHeightData heightData = default;
            WaterSurfaceData<SurfaceWater> waterData = default;
            TakeSurfaceSnapshot(ref heightData, ref waterData);

            probes = NetWaterProfilePin.ProbesFor(lengthXZ);
            float3 previous = startPosition;
            for (int i = 0; i < probes; i++)
            {
                float t = math.lerp(range.x, range.y, (float)i / (probes - 1));
                float3 p = i == 0 ? startPosition
                    : i == probes - 1 ? endPosition
                    : MathUtils.Position(source, t);

                float terrain, water, depth;
                WaterUtils.SampleHeight(ref waterData, ref heightData, p, out terrain, out water, out depth);

                _profileTerrain[i] = terrain;
                _profileDepth[i] = depth;
                _profileSurface[i] = NetWaterProfilePin.SurfaceHeight(terrain, water, depth,
                    info.ElevationLimit);
                _profileDistance[i] = i == 0 ? 0f : math.distance(previous.xz, p.xz);
                previous = p;
            }

            if (!NetWaterProfilePin.CrossesWater(_profileDepth, probes))
            { _profileVerdict = "dry"; return false; }
            _profileTouchedWater = true;
            _profileTraceWorthy = true;

            // Both endpoint heights are the ones on the wire, free height or not. `surface +
            // elevation` looks like the right formula and is not: over water an endpoint's elevation
            // is measured from the TERRAIN (that is how the committed Elevation is derived) while
            // the surface here is the water plus bridge clearance, so adding the two counts the
            // lake's depth twice. Measured 2026-09-02 on a live span: elevation 67.37 over a
            // surface of 514.91 predicts 582.29 for a road the tool had put at 516.93 - 65 m out,
            // exactly the depth of the lake under it. The tool's own control point is already at
            // the height the span commits at, on land and over water alike.
            float startHeight = startPosition.y;
            float endHeight = endPosition.y;
            if (!math.isfinite(startHeight) || !math.isfinite(endHeight))
            { _profileVerdict = "endpoint height is not finite"; return false; }

            NetWaterProfilePin.PredictDeck(_profileSurface, _profileTerrain, _profileDistance, probes,
                startHeight, endHeight, command.Start.ElevationLeft, command.End.ElevationLeft,
                info.ElevationLimit, info.MaxSlopeSteepness, _profileDeck);

            _profileDeckReady = true;
            pieces = NetWaterProfilePin.Simplify(_profileDeck, _profileDistance, probes,
                NetWaterProfilePin.ChordTolerance, NetWaterProfilePin.MaxPieces, _profileBreaks);
            return pieces >= 1;
        }

        /// <summary>
        /// Whether a committed edge sent on the geometry-only path should carry the pin: it crosses
        /// water, and its own deck is the straight line between its two end nodes - the one shape a
        /// pinned course reproduces. The committed curve IS the deck here, so nothing is predicted.
        /// </summary>
        private bool ShouldPinCommittedEdge(Entity prefab, Bezier4x3 curve,
            float2 startElevation, float2 endElevation)
        {
            NetPrefabInfo info = NetInfoOf(prefab);
            // Same exemption as the intent path. A committed edge has no free-height ends: its two
            // node heights are what they are, and both travel.
            if (!NetWaterProfilePin.NeedsPin(startElevation.x, endElevation.x, info.ElevationLimit,
                    info.RequireElevated, false, false))
            {
                _capSelfAnchoredSpans++;
                return false;
            }
            if (!NetWaterProfilePin.IsEligible(true, true, info.HasElevationRange,
                    info.ElevationRangeMin, info.ElevationRangeMax, info.ElevationLimit))
                return false;

            float lengthXZ = MathUtils.Length(curve.xz);
            if (!(lengthXZ > NetPlacementCommand.MinCourseLength)) return false;

            TerrainHeightData heightData = default;
            WaterSurfaceData<SurfaceWater> waterData = default;
            TakeSurfaceSnapshot(ref heightData, ref waterData);

            int probes = NetWaterProfilePin.ProbesFor(lengthXZ);
            float3 previous = curve.a;
            for (int i = 0; i < probes; i++)
            {
                float3 p = MathUtils.Position(curve, (float)i / (probes - 1));
                float terrain, water, depth;
                WaterUtils.SampleHeight(ref waterData, ref heightData, p, out terrain, out water, out depth);
                _profileDepth[i] = depth;
                _profileDeck[i] = p.y;
                _profileDistance[i] = i == 0 ? 0f : math.distance(previous.xz, p.xz);
                previous = p;
            }
            if (!NetWaterProfilePin.CrossesWater(_profileDepth, probes)) return false;

            return NetWaterProfilePin.Simplify(_profileDeck, _profileDistance, probes,
                NetWaterProfilePin.ChordTolerance, NetWaterProfilePin.MaxPieces, _profileBreaks) == 1;
        }

        /// <summary>
        /// Commit this course with its deck pinned: the endpoint elevations move to +/- the prefab's
        /// elevation limit, which collapses the generator's clamp band onto the two endpoint heights,
        /// and free-height resolution is dropped so neither end is re-measured against the local
        /// surface. The pin values never reach the entities - course splitting re-derives every
        /// committed elevation from the final geometry afterwards.
        /// </summary>
        private void ApplyProfilePin(Entity prefab,
            ref uint startFlags, float startY, Entity startSnap, int startKind, float startT,
            ref float2 startElevation,
            ref uint endFlags, float endY, Entity endSnap, int endKind, float endT,
            ref float2 endElevation)
        {
            NetPrefabInfo info = NetInfoOf(prefab);
            bool startPinnable = EndpointPinnable(startSnap, startKind, startT, startY);
            bool endPinnable = EndpointPinnable(endSnap, endKind, endT, endY);
            if (!NetWaterProfilePin.IsEligible(startPinnable, endPinnable, info.HasElevationRange,
                    info.ElevationRangeMin, info.ElevationRangeMax, info.ElevationLimit))
            {
                _rzPinRefused++;
                // A refused pin rebuilds its deck from local water, so say which end refused it and
                // at what height - that is the difference the deformed span is made of.
                SyncLog.Detail(LogTopic.Nets, "NetSync water pin refused: start[kind=" + startKind +
                    " sourceY=" + startY.ToString("F2") + " pinnable=" + startPinnable +
                    "] end[kind=" + endKind + " sourceY=" + endY.ToString("F2") +
                    " pinnable=" + endPinnable + "] range=" + info.ElevationRangeMin.ToString("F1") +
                    ".." + info.ElevationRangeMax.ToString("F1") +
                    " limit=" + info.ElevationLimit.ToString("F2"));
                return;
            }

            startFlags &= ~(uint)CoursePosFlags.FreeHeight;
            endFlags &= ~(uint)CoursePosFlags.FreeHeight;
            startElevation = NetWaterProfilePin.PinnedStartElevation(info.ElevationLimit);
            endElevation = NetWaterProfilePin.PinnedEndElevation(info.ElevationLimit);
            _rzPinnedSpans++;
        }

        /// <summary>
        /// Whether this endpoint's height is the one the pin band may be anchored at. A fresh node
        /// takes the transmitted height verbatim. An endpoint that landed on existing geometry only
        /// qualifies while that geometry sits at the source's height too - otherwise the band would
        /// be anchored somewhere the committed node is not.
        /// </summary>
        private bool EndpointPinnable(Entity snap, int kind, float t, float sourceY)
        {
            if (kind == KindFree || kind == KindMergeBatch) return true;
            // The target went stale between resolve and here, so this course plants a fresh node at
            // the transmitted position after all.
            if (snap == Entity.Null) return true;
            if (!EntityManager.Exists(snap)) return false;

            float localY;
            if (kind == KindReuseNode || kind == KindReuseConnector)
            {
                if (!EntityManager.HasComponent<Node>(snap)) return false;
                localY = EntityManager.GetComponentData<Node>(snap).m_Position.y;
            }
            else if (kind == KindSplit)
            {
                if (!EntityManager.HasComponent<Curve>(snap)) return false;
                localY = MathUtils.Position(EntityManager.GetComponentData<Curve>(snap).m_Bezier,
                    math.clamp(t, 0f, 1f)).y;
            }
            else return false;

            return math.abs(localY - sourceY) <= SurfaceAgreementTol;
        }

        private static Bezier4x3 SourceCurve(NetPlacementCommand command) => new Bezier4x3(
            new float3(command.Ax, command.Ay, command.Az),
            new float3(command.Bx, command.By, command.Bz),
            new float3(command.Cx, command.Cy, command.Cz),
            new float3(command.Dx, command.Dy, command.Dz));
    }
}
