using System.Collections.Generic;
using Colossal.Mathematics;
using Game.Net;
using Game.Prefabs;
using Game.Simulation;
using Game.Tools;
using Unity.Entities;
using Unity.Mathematics;

using CS2MultiplayerMod.Game.Sync.Commands;
using CS2MultiplayerMod.Game.Sync.Infrastructure;

namespace CS2MultiplayerMod.Game.Sync.Systems.Net
{
    // Vertical-profile transport for NetSyncSystem. A course carries two endpoints; the deck between
    // them is regenerated by whichever machine realizes it, from ITS terrain and ITS water sampled
    // every ~4 m. Terrain is replicated, water is live simulation state and is not, so a span over
    // water lands at the realizing machine's water height - correct end nodes, wrong deck. Capture
    // measures the deck it is committing and hands the receiver a form that needs no water at all;
    // see NetWaterProfilePin for the generator behaviour this mirrors.
    public partial class NetSyncSystem
    {
        private readonly float[] _profileSurface = new float[NetWaterProfilePin.ProbeCount];
        private readonly float[] _profileTerrain = new float[NetWaterProfilePin.ProbeCount];
        private readonly float[] _profileDepth = new float[NetWaterProfilePin.ProbeCount];
        private readonly float[] _profileDistance = new float[NetWaterProfilePin.ProbeCount];
        private readonly float[] _profileDelta = new float[NetWaterProfilePin.ProbeCount];
        private readonly float[] _profileDeck = new float[NetWaterProfilePin.ProbeCount];
        private readonly float3[] _profilePoint = new float3[NetWaterProfilePin.ProbeCount];
        private readonly int[] _profileBreaks = new int[NetWaterProfilePin.MaxPieces + 1];
        private readonly List<NetPlacementCommand> _profileExpanded = new List<NetPlacementCommand>();

        // 5 s counters. Capture: spans measured over water and the pinned pieces they became.
        // Realize: pinned spans committed, and pins this machine had to refuse - a refused span
        // rebuilds its deck from local water again, so a standing figure here is worth chasing.
        private int _capPinnedSpans, _capPinnedPieces;
        private int _rzPinnedSpans, _rzPinRefused;

        /// <summary>
        /// Replace every course of a captured operation that crosses water with the pinned pieces
        /// reproducing the deck this machine is committing. Runs once, at publish: the probe reads
        /// the terrain and water surfaces, and the definition cache is rebuilt on every preview frame.
        /// </summary>
        private void ExpandWaterProfilePins(List<NetPlacementCommand> courses)
        {
            if (courses.Count == 0) return;

            var expanded = new List<NetPlacementCommand>(courses.Count);
            bool changed = false;
            for (int i = 0; i < courses.Count; i++)
            {
                _profileExpanded.Clear();
                AppendCapturedCourse(courses[i], _profileExpanded);
                expanded.AddRange(_profileExpanded);
                changed |= _profileExpanded.Count != 1 || _profileExpanded[0] != courses[i];
            }
            if (!changed || expanded.Count > NetPlacementCommand.MaxCoursesPerOperation) return;

            courses.Clear();
            courses.AddRange(expanded);
        }

        /// <summary>
        /// The same for a mixed operation, whose placements are interleaved with deletes and
        /// replaces: each placement expands in place and every other item keeps its position.
        /// </summary>
        private void ExpandWaterProfilePins(List<LocalNetToolOperationItem> items)
        {
            if (items.Count == 0) return;

            var expanded = new List<LocalNetToolOperationItem>(items.Count);
            bool changed = false;
            for (int i = 0; i < items.Count; i++)
            {
                LocalNetToolOperationItem item = items[i];
                if (item.CommandId != NetPlacementCommand.Id || item.Placement == null)
                {
                    expanded.Add(item);
                    continue;
                }

                _profileExpanded.Clear();
                AppendCapturedCourse(item.Placement, _profileExpanded);
                changed |= _profileExpanded.Count != 1 || _profileExpanded[0] != item.Placement;
                for (int p = 0; p < _profileExpanded.Count; p++)
                    expanded.Add(new LocalNetToolOperationItem
                    {
                        CommandId = NetPlacementCommand.Id,
                        Original = p == 0 ? item.Original : Entity.Null,
                        Placement = _profileExpanded[p],
                    });
            }
            if (!changed || expanded.Count > NetToolOperationCommand.MaxItems) return;

            items.Clear();
            items.AddRange(expanded);
        }

        /// <summary>
        /// Add the wire form of one captured course to <paramref name="into"/>: the command itself
        /// when the span never touches water, otherwise the measured deck as one or more pinned
        /// pieces whose endpoint heights are the ones this machine is committing.
        /// </summary>
        private void AppendCapturedCourse(NetPlacementCommand command, List<NetPlacementCommand> into)
        {
            int probes, pieces;
            if (!MeasurePinnableDeck(command, out probes, out pieces))
            {
                into.Add(command);
                return;
            }

            _capPinnedSpans++;
            _capPinnedPieces += pieces;

            if (pieces == 1)
            {
                command.PinProfile = true;
                command.Start.PosY = _profileDeck[0];
                command.End.PosY = _profileDeck[probes - 1];
                into.Add(command);
                return;
            }

            Bezier4x3 source = SourceCurve(command);
            var startFlags = (CoursePosFlags)command.Start.Flags;
            var endFlags = (CoursePosFlags)command.End.Flags;
            for (int p = 0; p < pieces; p++)
            {
                int from = _profileBreaks[p];
                int to = _profileBreaks[p + 1];
                float2 cut = new float2(_profileDelta[from], _profileDelta[to]);
                Bezier4x3 curve = MathUtils.Cut(source, cut);
                // Two neighbouring pieces share a node only on raw float3 equality of their endpoint
                // positions, so both sides of a boundary get the SAME value, bit for bit.
                float3 a = _profilePoint[from]; a.y = _profileDeck[from];
                float3 d = _profilePoint[to]; d.y = _profileDeck[to];
                curve.a = a;
                curve.d = d;

                float length = MathUtils.Length(source, new Bounds1(cut.x, cut.y));
                if (!(length > NetPlacementCommand.MinCourseLength)) length = MathUtils.Length(curve);

                var piece = new NetPlacementCommand
                {
                    HasNativeCourse = true,
                    PrefabName = command.PrefabName,
                    SubPrefabName = command.SubPrefabName,
                    Ax = curve.a.x, Ay = curve.a.y, Az = curve.a.z,
                    Bx = curve.b.x, By = curve.b.y, Bz = curve.b.z,
                    Cx = curve.c.x, Cy = curve.c.y, Cz = curve.c.z,
                    Dx = curve.d.x, Dy = curve.d.y, Dz = curve.d.z,
                    Length = length,
                    RandomSeed = command.RandomSeed,
                    CreationFlags = command.CreationFlags,
                    CourseElevationLeft = command.CourseElevationLeft,
                    CourseElevationRight = command.CourseElevationRight,
                    FixedIndex = command.FixedIndex,
                    PinProfile = true,
                    Start = p == 0 ? command.Start : InteriorEndpoint(source, a, cut.x, startFlags),
                    End = p == pieces - 1 ? command.End : InteriorEndpoint(source, d, cut.y, endFlags),
                };
                if (p == 0) piece.Start.PosY = a.y;
                if (p == pieces - 1) piece.End.PosY = d.y;
                // Each piece carries its own cut curve, so its parameter range is the whole of it.
                piece.Start.CourseDelta = 0f;
                piece.End.CourseDelta = 1f;
                into.Add(piece);
            }
        }

        /// <summary>
        /// Sample the deck this machine is committing for <paramref name="command"/> and, when it
        /// crosses water, fill <see cref="_profileBreaks"/> with the probe indices dividing it into
        /// straight pieces. False when the span never touches water or cannot be pinned at all - the
        /// caller then sends it exactly as captured.
        /// </summary>
        private bool MeasurePinnableDeck(NetPlacementCommand command, out int probes, out int pieces)
        {
            probes = 0;
            pieces = 0;
            if (!command.HasNativeCourse || command.PinProfile) return false;

            // A fixed-element net (a dam) is divided by its own element table and must not be
            // pre-divided here; an owned sub-net already commits at its absolute height, and a
            // tunnel measures against the terrain alone. None of the three depends on water.
            if (command.FixedIndex >= 0) return false;
            if (command.Start.ParentMesh >= 0 || command.End.ParentMesh >= 0) return false;
            if (command.Start.ElevationLeft < -1f || command.End.ElevationLeft < -1f) return false;

            Entity prefab;
            if (!_prefabIndex.TryResolve(command.PrefabName, out prefab)) return false;
            NetPrefabInfo info = NetInfoOf(prefab);
            if (!NetWaterProfilePin.IsEligible(true, true, info.HasElevationRange,
                    info.ElevationRangeMin, info.ElevationRangeMax, info.ElevationLimit))
                return false;

            float2 range = new float2(command.Start.CourseDelta, command.End.CourseDelta);
            if (!math.isfinite(range.x) || !math.isfinite(range.y) || range.y <= range.x) return false;

            Bezier4x3 source = SourceCurve(command);
            float lengthXZ = MathUtils.Length(MathUtils.Cut(source, range).xz);
            if (!(lengthXZ > NetPlacementCommand.MinCourseLength)) return false;

            var startPosition = new float3(command.Start.PosX, command.Start.PosY, command.Start.PosZ);
            var endPosition = new float3(command.End.PosX, command.End.PosY, command.End.PosZ);

            TerrainHeightData heightData = default;
            WaterSurfaceData<SurfaceWater> waterData = default;
            TakeSurfaceSnapshot(ref heightData, ref waterData);

            probes = NetWaterProfilePin.ProbesFor(lengthXZ);
            float3 previous = startPosition;
            for (int i = 0; i < probes; i++)
            {
                float t = math.lerp(range.x, range.y, (float)i / (probes - 1));
                float3 p = i == 0 ? startPosition
                    : i == probes - 1 ? endPosition
                    : MathUtils.Position(source, t);

                float terrain, water, depth;
                WaterUtils.SampleHeight(ref waterData, ref heightData, p, out terrain, out water, out depth);

                _profileTerrain[i] = terrain;
                _profileDepth[i] = depth;
                _profileSurface[i] = NetWaterProfilePin.SurfaceHeight(terrain, water, depth,
                    info.ElevationLimit);
                _profileDistance[i] = i == 0 ? 0f : math.distance(previous.xz, p.xz);
                _profileDelta[i] = t;
                _profilePoint[i] = p;
                previous = p;
            }

            if (!NetWaterProfilePin.CrossesWater(_profileDepth, probes)) return false;

            bool startFree = ((CoursePosFlags)command.Start.Flags & CoursePosFlags.FreeHeight) != 0;
            bool endFree = ((CoursePosFlags)command.End.Flags & CoursePosFlags.FreeHeight) != 0;
            float startHeight = startFree
                ? _profileSurface[0] + command.Start.ElevationLeft
                : startPosition.y;
            float endHeight = endFree
                ? _profileSurface[probes - 1] + command.End.ElevationLeft
                : endPosition.y;
            if (!math.isfinite(startHeight) || !math.isfinite(endHeight)) return false;

            NetWaterProfilePin.PredictDeck(_profileSurface, _profileTerrain, _profileDistance, probes,
                startHeight, endHeight, info.MaxSlopeSteepness, _profileDeck);

            pieces = NetWaterProfilePin.Simplify(_profileDeck, _profileDistance, probes,
                NetWaterProfilePin.ChordTolerance, NetWaterProfilePin.MaxPieces, _profileBreaks);
            return pieces >= 1;
        }

        /// <summary>
        /// Whether a committed edge sent on the geometry-only path should carry the pin: it crosses
        /// water, and its own deck is the straight line between its two end nodes - the one shape a
        /// pinned course reproduces. The committed curve IS the deck here, so nothing is predicted.
        /// </summary>
        private bool ShouldPinCommittedEdge(Entity prefab, Bezier4x3 curve)
        {
            NetPrefabInfo info = NetInfoOf(prefab);
            if (!NetWaterProfilePin.IsEligible(true, true, info.HasElevationRange,
                    info.ElevationRangeMin, info.ElevationRangeMax, info.ElevationLimit))
                return false;

            float lengthXZ = MathUtils.Length(curve.xz);
            if (!(lengthXZ > NetPlacementCommand.MinCourseLength)) return false;

            TerrainHeightData heightData = default;
            WaterSurfaceData<SurfaceWater> waterData = default;
            TakeSurfaceSnapshot(ref heightData, ref waterData);

            int probes = NetWaterProfilePin.ProbesFor(lengthXZ);
            float3 previous = curve.a;
            for (int i = 0; i < probes; i++)
            {
                float3 p = MathUtils.Position(curve, (float)i / (probes - 1));
                float terrain, water, depth;
                WaterUtils.SampleHeight(ref waterData, ref heightData, p, out terrain, out water, out depth);
                _profileDepth[i] = depth;
                _profileDeck[i] = p.y;
                _profileDistance[i] = i == 0 ? 0f : math.distance(previous.xz, p.xz);
                previous = p;
            }
            if (!NetWaterProfilePin.CrossesWater(_profileDepth, probes)) return false;

            return NetWaterProfilePin.Simplify(_profileDeck, _profileDistance, probes,
                NetWaterProfilePin.ChordTolerance, NetWaterProfilePin.MaxPieces, _profileBreaks) == 1;
        }

        /// <summary>
        /// Commit this course with its deck pinned: the endpoint elevations move to +/- the prefab's
        /// elevation limit, which collapses the generator's clamp band onto the two endpoint heights,
        /// and free-height resolution is dropped so neither end is re-measured against the local
        /// surface. The pin values never reach the entities - course splitting re-derives every
        /// committed elevation from the final geometry afterwards.
        /// </summary>
        private void ApplyProfilePin(Entity prefab,
            ref uint startFlags, float startY, Entity startSnap, int startKind, float startT,
            ref float2 startElevation,
            ref uint endFlags, float endY, Entity endSnap, int endKind, float endT,
            ref float2 endElevation)
        {
            NetPrefabInfo info = NetInfoOf(prefab);
            bool startPinnable = EndpointPinnable(startSnap, startKind, startT, startY);
            bool endPinnable = EndpointPinnable(endSnap, endKind, endT, endY);
            if (!NetWaterProfilePin.IsEligible(startPinnable, endPinnable, info.HasElevationRange,
                    info.ElevationRangeMin, info.ElevationRangeMax, info.ElevationLimit))
            {
                _rzPinRefused++;
                return;
            }

            startFlags &= ~(uint)CoursePosFlags.FreeHeight;
            endFlags &= ~(uint)CoursePosFlags.FreeHeight;
            startElevation = NetWaterProfilePin.PinnedStartElevation(info.ElevationLimit);
            endElevation = NetWaterProfilePin.PinnedEndElevation(info.ElevationLimit);
            _rzPinnedSpans++;
        }

        /// <summary>
        /// Whether this endpoint's height is the one the pin band may be anchored at. A fresh node
        /// takes the transmitted height verbatim. An endpoint that landed on existing geometry only
        /// qualifies while that geometry sits at the source's height too - otherwise the band would
        /// be anchored somewhere the committed node is not.
        /// </summary>
        private bool EndpointPinnable(Entity snap, int kind, float t, float sourceY)
        {
            if (kind == KindFree || kind == KindMergeBatch) return true;
            // The target went stale between resolve and here, so this course plants a fresh node at
            // the transmitted position after all.
            if (snap == Entity.Null) return true;
            if (!EntityManager.Exists(snap)) return false;

            float localY;
            if (kind == KindReuseNode || kind == KindReuseConnector)
            {
                if (!EntityManager.HasComponent<Node>(snap)) return false;
                localY = EntityManager.GetComponentData<Node>(snap).m_Position.y;
            }
            else if (kind == KindSplit)
            {
                if (!EntityManager.HasComponent<Curve>(snap)) return false;
                localY = MathUtils.Position(EntityManager.GetComponentData<Curve>(snap).m_Bezier,
                    math.clamp(t, 0f, 1f)).y;
            }
            else return false;

            return math.abs(localY - sourceY) <= SurfaceAgreementTol;
        }

        /// <summary>
        /// A course boundary this capture introduced: a fresh node on the source curve carrying the
        /// side/mode flags the game's own mid-course cuts propagate, and nothing else.
        /// </summary>
        private static NetEndpointIntent InteriorEndpoint(Bezier4x3 source, float3 position,
            float delta, CoursePosFlags sourceFlags)
        {
            const CoursePosFlags carried = CoursePosFlags.IsParallel | CoursePosFlags.IsRight |
                                           CoursePosFlags.IsLeft | CoursePosFlags.IsGrid;
            quaternion rotation = NetUtils.GetNodeRotation(MathUtils.Tangent(source, delta));
            return new NetEndpointIntent
            {
                Kind = NetEndpointTargetKind.Free,
                PosX = position.x, PosY = position.y, PosZ = position.z,
                RotX = rotation.value.x, RotY = rotation.value.y,
                RotZ = rotation.value.z, RotW = rotation.value.w,
                Flags = (uint)(sourceFlags & carried),
                ParentMesh = -1,
                AnchorX = position.x, AnchorY = position.y, AnchorZ = position.z,
            };
        }

        private static Bezier4x3 SourceCurve(NetPlacementCommand command) => new Bezier4x3(
            new float3(command.Ax, command.Ay, command.Az),
            new float3(command.Bx, command.By, command.Bz),
            new float3(command.Cx, command.Cy, command.Cz),
            new float3(command.Dx, command.Dy, command.Dz));
    }
}
